version: '3.8'
services:
  rag-chat:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
      - STREAMLIT_BROWSER_GATHER_USAGE_STATS=false
      - STREAMLIT_THEME_BASE=light
      - STREAMLIT_SERVER_RUN_ON_SAVE=true
    command: streamlit run app.py --server.runOnSave true --server.address 0.0.0.0


